선택된 Battle Tag Item 들에 대한 Dialog 및 삭제기능 추가
kaki104/diablo3hub pull request #8
Opened 2017-06-05 15:57 UTC by happyjem

선택된 Battle Tag Item 들에 대한 Dialog 및 삭제기능 추가

2017-06-07 11:54 UTC, kaki104 requested changes

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/Controls/BattleTagItemDelConfirmDialog.xaml
> +        ItemsSource="{Binding SelectedBattleTags}" Height="120" >
리스트뷰에 기본적으로 지정되어있는 스크롤 뷰어 설정을 사용하면 될 것 같은데..옵션을 조정하신이유가 가로 스크롤을 위해서 만드신건가요? 어떤 결과가 나올지 모르겠는데..이미지 한번만 보여주세요

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/Diablo3Hub.csproj
> +    <PackageReference Include="MvvmLight">
MVVMLight 사용 여부에 대해서는 영철님과 함께 이야기를 해보시죠

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/Diablo3Hub.csproj
> +      <Version>1.3.3</Version>
SQLite 들의 경우 한달에 한두번씩 계속 버전업이 됩니다. 그래서 중간 중간 버전업을 하지 않을려고 합니다. 될 수 있으면 기존 버전으로 맞추어주세요

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/Diablo3Hub.csproj
> +    <SDKReference Include="SQLite.UWP.2015, Version=3.19.2">
SQLite 들의 경우 한달에 한두번씩 계속 버전업이 됩니다. 그래서 중간 중간 버전업을 하지 않을려고 합니다. 될 수 있으면 기존 버전으로 맞추어주세요

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/Services/DBHelper.cs
> +            var paramStr = tagIds.Aggregate((startTagId, nextTagId) =>
var paramStr = string.Join(",", tagIds);
이렇게 사용하시면 좀 수월합니다.

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/ViewModels/BattleTagItemDelConfirmDialogViewModel.cs
> +                var selTags = SelectedBattleTags.ToList<BattleTag>();
다중 삭제를 에러없이 하기 위해서는 화면에 해당 아이템이 보이지 않도록 해야 제대로 삭제가 되었던 것으로 기억합니다.
아이템을 삭제하면 아마도, DB와 연결되어있던 녀석이 오류를 발생시키지 않는지..궁금합니다.

2017-06-07 11:54 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/ViewModels/BattleTagPageViewModel.cs
> +                var btItemDelConfirmViewModel = viewModelLocator.BattleTagItemDelConfirmDialogViewModel;
삭제 아이템 전달 방식이 좋지 않습니다. 뷰모델 로케이터는 뷰에서 바인딩을 하기 위한 용도로 주로 사용하는데..직접 적으로 데이터를 전달하는 것은 DI를 해치는 것으로 판단됩니다. 이런경우라면 Messenger를 이용해서 전달을 하거나 생성자에 직접 넣어서 호출하는 방법이 있을 것 같습니다.

2017-06-11 16:06 UTC, happyjem commented on Diablo3Hub/Diablo3Hub/Controls/BattleTagItemDelConfirmDialog.xaml
> +        ItemsSource="{Binding SelectedBattleTags}" Height="120" >
![2](https://user-images.githubusercontent.com/42398/27012483-432d1366-4f0b-11e7-9130-4643d31b9dc3.png)

2017-06-11 16:07 UTC, happyjem commented on Diablo3Hub/Diablo3Hub/Diablo3Hub.csproj
> +    <PackageReference Include="MvvmLight">
MVVMLight를 지우고 생성자를 이용하는 방법으로 변경중입니다.

2017-06-11 16:09 UTC, happyjem commented on Diablo3Hub/Diablo3Hub/Diablo3Hub.csproj
> +    <SDKReference Include="SQLite.UWP.2015, Version=3.19.2">
SQLite UWP 2015 같은 경우 Visual Studio 의 extension을 업데이트 하면, 버전이 올라가 버리네요. Nuget으로 설치되는 것이면 Downgrade 해 보겠는데, extension 쪽은 잘 모르겠습니다.

2017-06-11 16:16 UTC, happyjem commented on Diablo3Hub/Diablo3Hub/ViewModels/BattleTagItemDelConfirmDialogViewModel.cs
> +                var selTags = SelectedBattleTags.ToList<BattleTag>();
오류가 나지는 않았습니다. 제가 논리적인 오류가 있는것은 아닌지 확인 부탁드립니다.

2017-06-12 12:04 UTC, merged

2017-06-12 12:04 UTC, kaki104 reviewed
수정하신다고 고생하셨습니다. 우선 선 머지 후 수정하는 방향으로 하겠습니다.

2017-06-12 12:04 UTC, kaki104 commented on Diablo3Hub/Diablo3Hub/Diablo3Hub.csproj
> +    <SDKReference Include="SQLite.UWP.2015, Version=3.19.2">
그렇네요 extension은 다운그레이드도 앙대고 영..일단 최신버전으로 계속 올리는 방향으로 진행하겠습니다.